### ISSUE TITLE
error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joebalancio** [Pyppe/phantomjs2.0-ubuntu14.04x64#1]
Thanks for building this! Had to `sudo apt-get install libicu52` before I was able to execute the `phantomjs`. You may want to include a note in the README.

**Comment by Pyppe** [comment]
@joebalancio thanks for the info!

**Comment by damahua** [comment]
I tried this command. It did not work. 
It says Unable to locate package libicu52.

**Comment by dolohow** [comment]
Download from here
http://packages.ubuntu.com/trusty/amd64/libicu52/download

then do

```
dpkg -i libicu52_52.1-3ubuntu0.4_amd64.deb
```

**Comment by myselfsufiyan** [comment]
@dolohow thanks that works for me...

**Comment by hotrush** [comment]
@dolohow confirmed, that works. thanks!

**Comment by peterhurford** [comment]
On Ubuntu, I was able to add `deb http://security.ubuntu.com/ubuntu trusty-security main` to my `/etc/apt/sources.list` (as http://packages.ubuntu.com/trusty/amd64/libicu52/download suggests), and then I did `sudo apt-get udpdate`, and then `sudo apt-get install libicu52` worked and then phantom.js worked.

**Comment by vsimko** [comment]
In my case (ubuntu xenial), I wanted to install the `caret` R package when the problem occured.
I didn't have to install the `libicu52`, just `libicu55` and `libicu-dev`.
Then, inside Rstudio, I (updated) `stringi` and just in case also `stringr` package.
Then finally the `caret` and it worked.
(hopefully, this comment helps somebody)

**Comment by ghost** [comment]
@vsimko when you say updated stringi and stringr... what steps did you follow

**Comment by vsimko** [comment]
I think I updated `stringi` to version 1.2.2 and `stringr` to version 1.3.1
in R console in RStudio:
```r
install.packages(c("stringi", "stringr"))
```
