### ISSUE TITLE
"Segmentation fault" error when i run phantomjs 1.9.8

### ISSUE THREAD

**Issue by 92hackers** [Pyppe/phantomjs2.0-ubuntu14.04x64#5]
i download phantomjs 1.9.8,
and when i run it,  terminal displays "Segmentation fault",
how to solve it ?

**Comment by Pyppe** [comment]
This repository contains binaries for version 2.0; not 1.9.8. Closing issue for not being relevant to this repository.

For information about 1.9.8, see the official repository: https://github.com/ariya/phantomjs
